name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: WebApp
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: current
    
    - name: Install NPM packages
      run: npm install
      
    - name: Configure Git username
      run: git config user.name github-actions
      shell: bash
    
    - name: Configure Git email
      run: git config user.email github-actions@github.com
      shell: bash
    
    - name: Deploy web app
      run: npm run deploy
